services:
  - type: web
    name: payload-cms
    runtime: node
    plan: starter
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URI
        sync: false
      - key: PAYLOAD_SECRET
        generateValue: true
      - key: PAYLOAD_CONFIG_PATH
        value: src/payload.config.ts
      - key: PORT
        value: 10000